encoder: "microsoft/swin-base-patch4-window7-224"
decoder: "gpt2"

output_model: "models/sartor-finetuned"

train_pct: 0.95
train_batch_size: 8
val_batch_size: 8
lr: 2e-5
encoder_lr: 1e-6
seed: 42
grad_accum_steps: 4

logging_steps: 256
save_steps: 2048
warmup_steps: 256

eval_strategy: "steps"
eval_steps: 2048

max_length: 128
weight_decay: 0.01

epochs: 20

label_smoothing_factor: 0.0

decoder_frozen_layers: 6
encoder_frozen_stages: 2

caps_dir: "data/fine_tune/Text/Caption/train/Caption_train.csv"
imgs_dir: "data/fine_tune/SARimages_preprocessed/SARimages"
