encoder: "microsoft/swin-base-patch4-window7-224"
decoder: "gpt2"
output_model: "models/sartor-pretrained"

train_pct: 0.95
train_batch_size: 8
val_batch_size: 8
lr: 3e-4
seed: 42
grad_accum_steps: 4
logging_steps: 1024
save_steps: 2048
warmup_steps: 1024

max_length: 128
weight_decay: 0.01

epochs: 15

caps_dir: "data/pretrain/dataset_rsicd.json"
imgs_dir: "data/pretrain/RSICD_images/"